version: "3.8"

services:
  rails-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/rails
      - bashhistory:/commandhistory
      - rails-gems:/gems
    ports:
      - "3001:3001"
    command: bundle exec rails s -b '0.0.0.0' -p 3001

volumes:
  rails-gems:
  bashhistory:
